### ISSUE TITLE
Slider for Number Parameters Ignores Float step

### ISSUE THREAD

**Issue by brombomb** [gensyn/de_gensyn_HomeAssistantPlugin#39]
When attempting to call a Home Assistant script that has a number input field defined with float-based min, max, and step values, the slider UI element in StreamController does not seem to respect the specified float step.

My Home Assistant script has a "Volume" variable configured as follows:

```YAML
fields:
  volume:
    name: Volume
    description: Set the Volume
    selector:
      number:
        min: 0.1
        max: 1.0
        step: 0.1
    default: 0.2
```

When I use the slider in the StreamController UI to set this volume parameter, it doesn't allow adjustments in the defined 0.1 increments. It appears to either jump in whole numbers or does not allow for precise float value selection.

✅ Expected Behavior
The slider in the StreamController UI should:

Allow adjustments in increments matching the step value defined in the Home Assistant script's number selector (e.g., 0.1, 0.2, 0.3, ..., 1.0).
Visually reflect these float steps.
Send the selected float value correctly to the Home Assistant service when the action is triggered.

Here's the entire script in case you don't want to create one on your own:

```yaml
alias: Universal Music Toggle
sequence:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state(target_speaker, 'playing') }}"
        sequence:
          - service: media_player.media_stop
            target:
              entity_id: "{{ target_speaker }}"
    default:
      - service: media_player.volume_set
        target:
          entity_id: "{{ target_speaker }}" 
        data:
          volume_level: "{{ (volume | default(0.2)) | float }}"
      - service: media_player.play_media
        target:
          entity_id: "{{ target_speaker }}" 
        data:
          media_content_id: media-source://radio_browser/962cc6df-0601-11e8-ae97-52543be04c81
          media_content_type: audio/mpeg
mode: single
fields:
  target_speaker:
    name: Target Speaker
    description: Speaker
    required: false
    default: media_player.office_speaker
    selector:
      entity:
        domain: media_player
        multiple: false
  volume:
    name: Volume
    description: Set the Volume
    default: 0.2 # This is the intended default value
    selector:
      number:
        min: 0.1
        max: 1
        step: 0.1
description: Play DanceWave on the given speaker at a set volume
icon: mdi:speaker-play
```
